app:
  environment: production
  port: 8081
  gracefulShutdownTime: 10s

logger:
  level: info

apiKey:
  enabled: true
  allowedApiKeys: 
    apitest: true

cache:
  name: 1
  host: localhost
  port: 6379
  poolSize: 20
  minIdleConns: 5
  dialTimeout: 5s
  readTimeout: 3s
  writeTimeout: 3s
  connectRetries: 3
  retryInterval: 10s
  ttl: 10m 

couponConfig:
  ignoreUnzipErrors: true
  bloomKey: promo_filter
  exactSet: promo_exact
  batchSize: 1000
  files:
    - "./data/couponbase1.gz"
    - "./data/couponbase2.gz"
    - "./data/couponbase3.gz"
  validation:
    minLength: 8
    maxLength: 10
    allowedCharacters: uppercase