app:
  environment: production

  server:
    gracefulShutdownTime: 10s
    compression: true
    port: 8081

logger:
  level: info

apiKey:
  enabled: true
  allowedApiKeys: 
    apitest: true

cache:
  name: 1
  # host: kart-cache
  host: localhost
  password: password
  port: 6379
  poolSize: 20
  minIdleConns: 5
  dialTimeout: 5s
  readTimeout: 3s
  writeTimeout: 3s
  connectRetries: 3
  retryInterval: 10s
  ttl: 10m 

database:
  debug: true
  name: kart_challenge
  # host:  kart-db
  host:  localhost
  username: admin
  password: password
  port: 5432
  # timezone: Asia/Kolkata
  sslmode: disable
  maxIdleConns: 100
  maxOpenConns: 500
  connMaxLife: 2m
  connMaxIdle: 1m
  connectRetries: 3
  retryInterval: 10s

couponConfig:
  ignoreUnzipErrors: false
  bloomKey: promo_filter
  exactSet: promo_exact
  batchSize: 1000
  files:
    - "./data/couponbase1.gz"
    - "./data/couponbase2.gz"
    - "./data/couponbase3.gz"
  validation:
    minLength: 8
    maxLength: 10
    allowedCharacters: uppercase